### ISSUE TITLE
Simple feature improvements/macros

### ISSUE THREAD

**Issue by bilow-factual** [spencertipping/ni#12]
- [x] `^HR<n>`: set hadoop/jobconf number of reducers to <n>
- [x] maybe some `HS` thing where the output directories and the input directories are listed in the same row..
- [ ] `f$` to get last column

**Comment by spencertipping** [comment]
I love all of these!

`^HR` can be a short op that generates a config meta-operation, just like `^{` is now. That's an easy one.

The `HS` one is more involved but not bad at all. I can write up a new alternative for `H`.

`f$` should be easy, but isn't quite yet -- I need to think about the best way to add this to the colspec grammar.

**Comment by bilow-factual** [comment]
Yep, I plan on trying to implement them if they're easy enough. Another one that I'm gonna macro-ify, this to something like:

- [x] `p'sub mrif(n)` `^{@split_fn=split "/", $ENV{mapreduce_map_input_file}; $input_dir = join "/", @split_fn[$#split_fn-3..$#split_fn] }`

**Comment by bilow-factual** [comment]
Hadoop directory health `HDH`

~- [ ] Haven't thought this one out completely, but something that will give a quick check that none of your directories are too much larger (say, 3-5x) larger than the median. `HS[rE-5 w[n] r~1 fB] _ [O]` maybe~

**Comment by bilow-factual** [comment]
most of these were bad ideas. not sure how to do `f$`; you can do it with bash expansion, but apparently not with `cut`, which `f` uses.

http://stackoverflow.com/questions/22727107/how-to-find-the-last-field-using-cut

**Comment by spencertipping** [comment]
i think it would be totally fine to bypass `cut` for `f$`. `f` only uses `cut` when the fields are selected in order (`cut` requires this) -- otherwise it falls back to the slower but more general perl implementation.

**Comment by bilow-factual** [comment]
Haven't found a use for `f$`. Closing.
