### ISSUE TITLE
lazytest tricky error with whitespace after triple backticks

### ISSUE THREAD

**Issue by bilow-factual** [spencertipping/ni#18]
lazytest errors out in a tricky way when there is whitespace after the triple backticks; this error is easy-ish to recognize, but kind of hard to remember, and also hard to fix because the thing lazytest doesn't like is nearly invisible.

See, for example, e9a27f4 which has that error on line ~725 of `doc/ni_by_example_4.md`.

**Comment by spencertipping** [comment]
Awesome bug! Should be fixed now; also fixed in github.com/spencertipping/lazytest.
